# Generated by Django 2.2 on 2019-04-30 23:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomeCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inc_catname', models.CharField(max_length=45)),
                ('inc_catdetails', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Incomes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inc_ac', models.CharField(max_length=45)),
                ('amount', models.FloatField()),
                ('tran_date', models.DateField(default=django.utils.timezone.now)),
                ('receiv_by', models.CharField(max_length=45)),
                ('remark', models.TextField()),
                ('inc_catid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.IncomeCategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExpensesCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exp_catname', models.CharField(max_length=45)),
                ('exp_catdetails', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exp_ac', models.CharField(max_length=45)),
                ('amount', models.FloatField()),
                ('tran_date', models.DateField(default=django.utils.timezone.now)),
                ('pay_by', models.CharField(max_length=45)),
                ('remark', models.TextField()),
                ('exp_catid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.ExpensesCategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CashBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acc', models.CharField(max_length=45)),
                ('tran_date', models.DateField(default=django.utils.timezone.now)),
                ('amount', models.FloatField()),
                ('operation', models.CharField(max_length=45)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BankBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acc', models.CharField(max_length=45)),
                ('tran_date', models.DateField(default=django.utils.timezone.now)),
                ('amount', models.FloatField()),
                ('operation', models.CharField(max_length=45)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
